---

services:
  reverse-proxy:
    image: traefik:v3.0
    restart: unless-stopped
    user: root # TODO fix me
    ports:
      - "80:80"
      - "443:443"
      - "25:25"
      - "465:465"
      - "993:993"
    volumes:
      - "{{ traefik_home }}-dyn.yml:/etc/traefik-dyn.yml:ro"
      - "{{ traefik_home }}.yml:/etc/traefik.yml:ro"
      - "{{ acme_home }}/config/{{ cert.domain }}_ecc:/etc/certs"

  db:
    image: shawlynot/db:1
    restart: unless-stopped
    ports: 
     - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    # volumes:
    #   - database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "{{ db.POSTGRES_PASSWORD }}"
      POSTGRES_USER: admin
      ZITADEL_PG_PASS: {{ db.ZITADEL_PG_PASS }}
      THERAPY_PG_PASS: {{ db.THERAPY_PG_PASS }}

  zitadel:
    user: root
    restart: unless-stopped
    image: ghcr.io/zitadel/zitadel:latest
    command: start-from-init --config /config.yml --masterkey {{ zitadel.masterKey }} --tlsMode disabled
    volumes:
      - "{{ zitadel_home }}/config.yml:/config.yml:ro"
    depends_on:
      db:
        condition: service_healthy

volumes:
  database:
    driver: local
